### ISSUE TITLE
[Improvement] Broken Spawner Recipe

### ISSUE THREAD

**Issue by Itorius** [lilmoefow/DirtHuts-1.10.2#10]
I've come up with 3 ways that the broken spawner could be obtainable.

1) Easier Recipe - I'v made 2 options, [an easier one and a harder one](http://imgur.com/a/2zCyx)
2) Sell broken spawner shards for some other item(s)
3) I don't remember what it was :P

I'd personally go with the easier easier recipe since it's harder to obtain than the vanilla version (obtaining right from breaking the spawner) and you also need some infrastructure (SAG Mill, Alloy Smelter)

**Comment by lilmoefow** [comment]
Changed it to your first suggestion, It is available in the 0.8 update
