### ISSUE TITLE
Dupe Issues with GreifPrevention on Server

### ISSUE THREAD

**Issue by dutchvuurvos** [lilmoefow/DirtHuts-1.10.2#5]
When using the barrel from IE it doesnt empty the container with the creosote oil you try to put in.

Probably fixed in a newer version of IE. So you might wanna keep an eye on that!

**Comment by lilmoefow** [comment]
I feel like i have missed something in one of the permissions.  Gotta look into this more.

**Comment by lilmoefow** [comment]
Fixed with latest versions of Sponge and GriefPrevention
