### ISSUE TITLE
Mod Suggestions for Not-So-Distant future of pack

### ISSUE THREAD

**Issue by Justfines** [lilmoefow/DirtHuts-1.10.2#6]
- Crafting Tweaks, Which is a Crafting Q-o-L mod that adds buttons and shortcuts to multiple crafting GUIs (--planned)

- Tomb Many Graves, This is a gravestones-esque mod that has some fancy features. (I have tested version 2.1.10 on forge 2099 with SpongeForge version 1788; and have not observed any Keep inv like duping) -- This is to replace "Gravestones" (collection of graves by default is sneaking on top of grave) PLEASE CONFIRM (-- being tested)

- Just Enough Resources, addon to JEI that adds tables and information for misc item sources like Mob Drops (-- planned)

- Mouse Tweaks, tweaks to mouse controls for inventory and crafting. Includes mouse wheel-ing single items to and fro containers -- works in tandum to inv tweaks(made to do so infact), adds more precise mouse drag features (-- TBA.  includes picking up items by holding shift and dragging LMB on items, the vis versa, and other similar shortcuts.)

- Signals, a mod supplies Minecart routing and stations; Based on RL train systems (--planned)

- Substratum, adds common materials and alloys. Could be used as a standardized Ore generation mod, would require extra config changes. (-- has other plan for similar idea)

- Charset, Modular mod, IMO some possibly useful items (--on fence.  Understandable, its more of a general collection of items)

**Comment by Itorius** [comment]
I'd add Iron Chests mod

**Comment by lilmoefow** [comment]
- Crafting Tweaks (Can add next version)

- Tomb Many Graves (will test this before i update next)

- Just Enough Resources (Planned for next update)

- Mouse Tweaks (would this be a safe and more reliable mod to replace InvTweaks? or to work in tandem?)

-Signals ( that is planed already for next release)

-Substratum (Never heard of it, will check it out)

-Charset (I looked at it, but it didnt seem to actually add much)

-Iron chests (I forget why i left this one out)

-Mekanism (No, its 1.10.2 version is still quite the buggy mess and I have no interest in that mod)

-Bagginsis ( It is in the pack already, what have you been playing??)
