### ISSUE TITLE
Crash on crafting Engineer's Wire Cutters

### ISSUE THREAD

**Issue by ReactivePlatypus** [lilmoefow/DirtHuts-1.10.2#8]
Crafting Engineer's Wire cutters using any normal crafting table crashes the game.

Log: http://pastebin.com/xwMyK3sa

**Comment by lilmoefow** [comment]
Already Fixed in Dev aparently

https://github.com/malte0811/ImmersiveEngineering/commit/4ffa1f445cafd669b7ff9e80e46c8071a5ce6f45

Just waiting for that build to be pushed to Curse.

**Comment by lilmoefow** [comment]
Gonna close this, seeing as that script i wrote seems to bypass this crash "for now"
